added a short notice that failed tests will result in missing features, not in an compilation error, like with automake
--HG--
extra : convert_revision : svn%3A16f47a83-c923-0410-902c-c9163ce98875/trunk%401287

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -148,6 +148,10 @@ configtest()
 	fi
 }
 
+echo >&2 "Testing for optional external librarys."
+echo >&2 "If a test fails, some features will not be available."
+
+
 configtest qt4     QT
 if [[ "$NO_OPENSSL" == "0" ]]; then
     configtest openssl OPENSSL
